# Site settings
title: Iure Radin
description: Portfolio Iure Radin
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iureradin.github.io"

# User settings
username: Iure Radin
user_description: Hello, I am Iure Radin. I love operating systems, networks, automation and troubleshooting. I am currently looking for an opportunity as a DevOps
user_title: DevOps
email: iureradin@gmail.com
twitter_username: iureradin
github_username:  iureradin

exclude: ['package.json', 'src' , 'node_modules']
